name: pokedex
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter: 
    sdk: flutter
  badges: ^2.0.1
  get_storage: ^2.0.3
  percent_indicator: "^2.1.7+2"

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Pokemon
      fonts:
        - asset: assets/fonts/Pokemon Solid.ttf

